spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # JPA가 엔티티 기반으로 테이블 생성한 다음에 data.sql을 실행하도록 지연
    defer-datasource-initialization: true
    # JPA가 SQL을 어떤 DB용 문법으로 생성할지 결정
    database-platform: org.hibernate.dialect.MySQL57Dialect

  sql:
    init:
      mode: always

