spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
      # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      
    database-platform: org.hibernate.dialect.MySQL57Dialect
